version: "3"

services:
  api:
    container_name: api
    restart: always
    build: .
    env_file: .env
    ports:
      - 4000:4000
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
